[project]
name = "forklet"
version = "0.1.0"
description = "Download any file or folder from any GitHub repo by branch, tag, or commit with glob pattern filtering."
readme = "README.md"
license = {file = "LICENSE"}
authors = [{ name = "AllDotPy", email = "hello@alldotpy.com" }]
maintainers = [{ name = "#Einswilli", email = "einswilligoeh@email.com" }]
requires-python = ">=3.10"
keywords = [
    "forklet", "CI/CD", "github Downloader", "guardian",
    "pipelines", "iam", "secrets"
]

dependencies = [
    "pydantic>=2.11.9",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "typer>=0.18.0",
]

[project.optional-dependencies]
dev = [
    "black", 
    "mypy",
    "twine",
    "uv",
    "build",
    "pytest>=8.4.0", 
    "mkdocs>=1.6.1",
    "setuptools>=80.8.0",
    "mkdocs-material>=9.6.14",
    "mkdocs-static-i18n>=1.3.0",
]

[project.scripts]
valkyrie = "forklet.__main__:main"

[project.urls]
# Homepage = "https://alldotpy.github.io/FletX"
Repository = "https://github.com/AllDotPy/Forklet"
# Documentation = "https://alldotpy.github.io/FletX"
Tracker = "https://github.com/AllDotPy/Forklet/issues"

[tool.setuptools]
packages = ["forklet"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
